spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3307/mydb
    username: root
    password: '{cipher}d3d11f5d7516c98f9b9fccc6b53172614835cee41ef1896c88d94f85e584374a'
    driver-class-name: org.mariadb.jdbc.Driver

# token:
#   expiration_time: 8640000
#   secret: user_service_native_token


gateway:
  ip: 218.147.255.133


